FROM postgres:16-alpine

RUN apk add --no-cache \
    curl \
    python3 \
    bash \
    sed \
    gawk

COPY init-scripts/ /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/*.sh